services:
  mysql_1:
    image: percona/percona-server:8.0.36-28.1-multi
    command: --server-id=1
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_1:/var/lib/mysql
      - ${PWD}/my.cnf:/etc/my.cnf

  mysql_2:
    image: percona/percona-server:8.0.36-28.1-multi
    command: --server-id=2
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_2:/var/lib/mysql
      - ${PWD}/my.cnf:/etc/my.cnf

  mysql_3:
    image: percona/percona-server:8.0.36-28.1-multi
    command: --server-id=3
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_3:/var/lib/mysql
      - ${PWD}/my.cnf:/etc/my.cnf

volumes:
  mysql_1:
  mysql_2:
  mysql_3:
