SET GLOBAL read_only = ON;

CHANGE REPLICATION SOURCE TO
  SOURCE_HOST = 'mysql_1',
	SOURCE_PORT = 3306,
	SOURCE_USER = 'replica',
	SOURCE_PASSWORD = 'replica',
	SOURCE_AUTO_POSITION = 1;

START REPLICA;

