services:
  redis_1:
    image: bitnami/redis:7.0.11
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_REPLICATION_MODE=master

  redis_2:
    image: bitnami/redis:7.0.11
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis_1
      - REDIS_MASTER_PASSWORD=redis

  redis_sentinel_1:
    image: bitnami/redis-sentinel:7.0.11
    depends_on:
      - redis_1
      - redis_2
    environment:
      - REDIS_MASTER_HOST=redis_1
      - REDIS_MASTER_SET=redis-group
      - REDIS_MASTER_PASSWORD=redis
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=1000
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=2000

  redis_sentinel_2:
    image: bitnami/redis-sentinel:7.0.11
    depends_on:
      - redis_1
      - redis_2
    environment:
      - REDIS_MASTER_HOST=redis_1
      - REDIS_MASTER_SET=redis-group
      - REDIS_MASTER_PASSWORD=redis
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=1000
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=2000

  redis_sentinel_3:
    image: bitnami/redis-sentinel:7.0.11
    depends_on:
      - redis_1
      - redis_2
    environment:
      - REDIS_MASTER_HOST=redis_1
      - REDIS_MASTER_SET=redis-group
      - REDIS_MASTER_PASSWORD=redis
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=1000
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=2000
